---
driver_plugin: vagrant

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/boxes/opscode-ubuntu-12.04.box
  run_list:
  - recipe[apt]

suites:
- name: mysql
  run_list:
  - recipe[platform_packages]
  - recipe[orch_db]
  attributes:
    platform_packages:
      pkgs:
        - name: curl
    mysql:
      server_root_password: 'flargle'
      server_repl_password: 'flargle'
      server_debian_password: 'flargle'
    orch_db:
      db_type: mysql
      databases:
        - name: myapp
          user: tekh
          password: snargles

- name: postgres
  run_list:
  - recipe[platform_packages]
  - recipe[orch_db]
  attributes:
    platform_packages:
      pkgs:
        - name: curl
    postgresql:
      password:
        postgres: 'flargle'
    orch_db:
      db_type: postgres
      databases:
        - name: myapp
          user: tekh
          password: snargles
