---
driver_plugin: vagrant

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
    require_chef_omnibus: true
  run_list:
  - recipe[apt]

suites:
- name: mysql
  run_list:
  - recipe[platform_packages]
  - recipe[orch_db]
  attributes:
    platform_packages:
      pkgs:
        - name: curl
    mysql:
      server_root_password: 'flargle'
      server_repl_password: 'flargle'
      server_debian_password: 'flargle'
    orch_db:
      databases:
        - name: myapp
          user: tekh
          password: snargles
          type: mysql

- name: postgres
  run_list:
  - recipe[platform_packages]
  - recipe[orch_db]
  attributes:
    platform_packages:
      pkgs:
        - name: curl
    postgresql:
      password:
        postgres: 'flargle'
    orch_db:
      databases:
        - name: myapp
          user: tekh
          password: snargles
          type: postgres

- name: both
  run_list:
  - recipe[platform_packages]
  - recipe[orch_db]
  attributes:
    platform_packages:
      pkgs:
        - name: curl
    mysql:
      server_root_password: 'flargle'
      server_repl_password: 'flargle'
      server_debian_password: 'flargle'
    postgresql:
      password:
        postgres: 'flargle'
    orch_db:
      databases:
        - name: pg_db
          user: pg_user
          password: snargles1
          type: postgres
        - name: mysql_db
          user: mysql_user
          password: snargles2
          type: mysql
